version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: aws-peering-tags-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          context: "architect"
          name: push-aws-peering-tags-operator-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "aws-peering-tags-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "aws-peering-tags-operator"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-aws-peering-tags-operator-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

